name: Deploy GitHub Pages
description: Deploy repository content to GitHub Pages
runs:
  using: composite
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: '.'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5